/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoCallRouteImport } from './routes/video-call'
import { Route as IndexRouteImport } from './routes/index'

const VideoCallRoute = VideoCallRouteImport.update({
  id: '/video-call',
  path: '/video-call',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/video-call': typeof VideoCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/video-call': typeof VideoCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/video-call': typeof VideoCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/video-call'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/video-call'
  id: '__root__' | '/' | '/video-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoCallRoute: typeof VideoCallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-call': {
      id: '/video-call'
      path: '/video-call'
      fullPath: '/video-call'
      preLoaderRoute: typeof VideoCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoCallRoute: VideoCallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
